/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
 */
package Utils;

/**
 *
 * @author HP
 */
public enum TipoEvento {
    FACTURACION_PRODUCTOS,
    FACTURACION_PEDIDOS,
    ACTUALIZAR_RESERVAS,
    RECEPCIONAR_PRODUCTOS,
    RECEPCION_FACTURADA,
    AJUSTAR_INVENTARIO,
    NUEVA_VENTA,
    NUEVA_COMPRA,
    FACTURA_COMPRA_MODIFICADA,
    FACTURA_VENTA_MODIFICADA,
    ANTICIPO_CREADO,
    ANTICIPO_ELIMINADO,
    FACTURA_ANULADA,
    RECEPCION_ELIMINADO,
    PEDIDO_RECEPCIONADO,
    PEDIDO_FACTURADO,
    REEMBOLSO_ELIMINADO,
    REEMBOLSO_CREADO,
    PEDIDO_MODIFICADO,
    ANTICIPO_APLICADO,
    ANTICIPO_APLICADO_ELIMINADO,
    PAGO_PEDIDO_COMPRA_CREADO,
    PAGO_PEDIDO_COMPRA_ELIMINADO,
    PAGO_PEDIDO_COMPRA_REEMBOLSADO,
    REEMBOLSO_PAGO_PEDIDO_COMPRA_ELIMINADO,
    PAGO_PEDIDO_COMPRA_APLICADO,
    PAGO_PEDIDO_COMPRA_APLICADO_ELIMINADO,
    PEDIDO_ENTREGADO,
    PEDIDO_NO_ENTREGADO,
    ENTREGA_REPROGRAMADA,
    PEDIDO_PREPARADO,
    PEDIDO_FACTURACION,
    ESTADO_FACTURACION,
    ESTADO_PEDIDO
}
